#!/bin/bash
problem=$(echo $1 | tr '[:lower:]' '[:upper:]')
numFiles=$(shopt -s nullglob; files=($(pwd)/$problem/*.in); echo ${#files[@]};)

RED='\033[0;31m'
GREEN='\033[0;032m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'
UNDERLINE='\e[4m'

if [[ $numFiles -eq 0 ]]; then
	echo "No input files."
  echo "Specify the problem id."
  echo "Example: cprun c"
	exit
fi

function check_error() {
    if [ $? -ne 0 ]; then
        echo -e "$(basename $0): $1"
        exit -1
    fi
}


fla=0
g++ -std=c++17 -Wall -fsanitize=undefined -O2 $(pwd)/$problem/$problem.cpp || fla=1
if [ $fla -eq 1 ]
then
	echo -e "${RED}✘ Compilation Error${NC}"
	exit
fi

tempOutputFile=$(pwd)/$problem/tmp.txt
correct=0
for ((i = 1 ; i <= $numFiles ; i++)); do
	inputTextFile=$(pwd)/$problem/$i.in
	outputTextFile=$(pwd)/$problem/$i.out
	true > $tempOutputFile
	./a.out < $inputTextFile > $tempOutputFile
	check_error "Failure occurred while running output file!"

	# Checking diff between the files
	diffOutput=$(diff $outputTextFile $tempOutputFile)
	diffLines=$(echo "$diffOutput" | wc -l)
	if [ $diffLines -gt 1 ]; then
		echo -e "${RED}✘ Failed sample $i!${NC}"
		echo -e "--------------------\n>> Input:"
		cat $inputTextFile
		echo -e "--------------------\n>> Output:"
		cat $tempOutputFile
		echo -e "--------------------\n>> Expected:"
		cat $outputTextFile
		echo -e "--------------------\n"
	else
		echo -e "${GREEN}✓ Passed sample $i!${NC}"
		correct=`expr $correct + 1`
	fi
done
rm $tempOutputFile

color=
icon=
if [[ $correct -eq $numFiles ]]; then
	color=$GREEN
	icon="✓"
else
	color=$RED
	icon="✘"
fi
echo -e "\n\n${color}${icon} Passed [$correct/$numFiles] tests${NC}"
